### ISSUE TITLE
remove the "OPTION" from the optional clauses?

### ISSUE THREAD

**Issue by stevieflow** [OpenDataServices/worker-co-op-model-rules-company-limited-by-shares#6]
In the clauses where we had an option, we've left the text in as 

> OPTION 2: Collective Management

I can understand why this might be useful, but probably not what we intend.  I'd propose the relevant sections just have titles in line with others - eg

> Collective Management

Any thoughts @odscjames ?

**Comment by ghost** [comment]
Yes - our one should be clear. Done on to-xml branch
