### ISSUE TITLE
Need Reviewer

### ISSUE THREAD

**Issue by ghost** [OpenDataServices/worker-co-op-model-rules-company-limited-by-shares#7]
Pull request #5 is ready to go and I just want a reviewer to check it before I hit the button.

I want a reviewer to simply stick the XML from https://raw.githubusercontent.com/OpenDataServices/worker-co-op-model-rules-company-limited-by-shares/to-xml/worker_co_op_model_rules.xml into https://opendataservices.github.io/contract-xml-parser/

They should get a nice formatted page of our articles of association.

The task is to go get our existing articles of association from PLanio and make sure there are no differences in content between the two. Please list any content changes you find on this ticket!

I did the best I could when I was working on the XML originally, but I want a fresh second pair of eyes to check me and make sure. Thanks!

**Comment by stevieflow** [comment]
I found a first difference, but this might actually be that our PDF rules are incorrect

Existing rules - clause 15 - just has a) - and then clause 16 

> The Member or, at the option of the Member,

Whereas the new rules contain this as clause 15 b) (which seems to be correct?)

**Comment by ghost** [comment]
Thanks steven. I agree with you this version seems correct.

Just noticed, the second of 2 clauses in "Transfer of Equity Shares" is wrong.

**Comment by ghost** [comment]
"Declaration of Interest", second clause, "where to do so would amount to a breach of confidence." is on the wrong line

**Comment by ghost** [comment]
Fixed and merged.
